version: "3.6"

services:
    database:
        container_name: db
        image: postgres:13.0-alpine
        restart: always
        stdin_open: true
        environment: 
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports: 
            - ${DB_PORT}:5432
        volumes:
            - .data/postgres/db:/var/lib/postgresql/data
            - .data/postgres/logs:/var/log/postgresql
            - .data/postgres/confs:/etc/postgresql
    phoenix:
        container_name: backend
        build: 
            context: ./backend
            dockerfile: Dockerfile
        stdin_open: true
        restart: always
        ports: 
            - ${APP_HTTP_PORT}:${APP_HTTP_PORT}
            - ${APP_HTTPS_PORT}:${APP_HTTPS_PORT}
        volumes: 
            - ./backend:/app
        depends_on: 
            - database
        env_file:
            - .env
        command: sh -c "mix setup && mix phx.server"
          
